---
- hosts: all
  become: true

  vars_files:
    - vars/main.yml
    - vars/{{ ansible_os_family }}.yml

  handlers:
    - name: restart sshd
      service: name=sshd state=restarted

    - name: reload ufw
      service: name=ufw state=restarted

    - name: restart firewalld
      service: name=firewalld state=restarted enabled=yes

    - name: restart openvpn
      service: name=openvpn state=restarted

    - name: restart openvpn-server
      service: name=openvpn-server@server state=restarted enabled=yes

    - name: restart nginx
      service: name=nginx state=restarted enabled=yes

    - name: restart ovpn-admin
      systemd:
        state: restarted
        enabled: true
        daemon_reload: true
        name: ovpn-admin

  tasks:
    - include_tasks: tasks/epel/{{ ansible_distribution }}.yml
      when: ansible_os_family == 'RedHat'

    - import_tasks: tasks/routing/public-ip.yml

    - import_tasks: tasks/secure/secure-Debian.yml
      when: ansible_os_family == 'Debian'

    - import_tasks: tasks/secure/secure-RedHat.yml
      when: ansible_os_family == 'RedHat'

    - import_tasks: tasks/routing/routing-Debian.yml
      when: ansible_os_family == 'Debian'

    - import_tasks: tasks/routing/routing-RedHat.yml
      when: ansible_os_family == 'RedHat'

    - import_tasks: tasks/prepare/prepare.yml
