---
- sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: true

- name: Accept packets from VPN tunnel adaptor - ufw
  ufw:
    comment: Created by Ansible
    direction: in
    interface: tun0
    rule: allow

- ufw:
    rule: allow
    route: true
    comment: Created by Ansible
    src: 10.8.0.0/24
    dest: 0.0.0.0/0

- name: Setup nat table rules with MASQUERADE - ufw
  blockinfile:
    dest: /etc/ufw/before.rules
    state: present
    insertbefore: \*filter
    block: |
      # OpenVPN config
      *nat
      :POSTROUTING ACCEPT [0:0]
      -A POSTROUTING -s 10.8.0.0/24 -j MASQUERADE
      COMMIT
  notify:
    - reload ufw
