---
- name: restart ssh
  service: name=sshd state=restarted

- name: reload ufw
  service: name=ufw state=restarted

- name: restart firewalld
  service: name=firewalld state=restarted enabled=yes

- name: restart openvpn
  service: name=openvpn state=restarted

- name: restart openvpn-server
  service: name=openvpn-server@server state=restarted enabled=yes

- name: restart nginx
  service: name=nginx state=restarted enabled=yes

- name: restart ovpn-admin
  systemd:
    state: restarted
    enabled: true
    daemon_reload: true
    name: ovpn-admin
