---
- include_vars: "vars/{{ ansible_os_family }}.yml"

- import_tasks: tasks/routing/public-ip.yml

- import_tasks: tasks/routing/routing-Debian.yml
  when: ansible_os_family == 'Debian'

- import_tasks: tasks/routing/routing-RedHat.yml
  when: ansible_os_family == 'RedHat'

- import_tasks: tasks/prepare/prepare.yml

- import_tasks: tasks/prepare/ovpn-ui.yml
  when: ovpn_ui_install == true
